# Generated by Django 4.2.5 on 2023-10-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_usercomments_relatedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image2',
        ),
    ]
