# Generated by Django 4.2.5 on 2023-10-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_remove_articles_image1_remove_articles_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
