# Generated by Django 4.2.5 on 2023-10-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_articles_image1_articles_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='image2',
        ),
        migrations.AddField(
            model_name='articles',
            name='images1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='articles',
            name='images2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
