# Generated by Django 4.2.5 on 2023-10-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_remove_articles_image1_remove_articles_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='images1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='images2',
            new_name='image2',
        ),
    ]
